# Generated by Django 5.2.14 on 2026-07-22 17:07

import apps.projects.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('service_type', models.CharField(blank=True, max_length=160)),
                ('client_name', models.CharField(blank=True, max_length=160)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('draft', 'Подготовка'), ('discovery', 'Уточнение задачи'), ('waiting_payment', 'Ожидает оплату'), ('in_progress', 'В работе'), ('waiting_client', 'Ожидает клиента'), ('review', 'На согласовании'), ('support', 'На поддержке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=240)),
                ('starts_at', models.DateField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ProjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status', 'Статус'), ('message', 'Сообщение'), ('file', 'Файл'), ('payment', 'Оплата'), ('approval', 'Согласование'), ('site', 'Сайт'), ('note', 'Заметка')], default='status', max_length=24)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('client_visible', models.BooleanField(default=True)),
                ('client_seen_at', models.DateTimeField(blank=True, null=True)),
                ('manager_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_events', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project')),
            ],
            options={
                'verbose_name': 'Событие проекта',
                'verbose_name_plural': 'События проекта',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('file', models.FileField(upload_to=apps.projects.validators.project_file_upload_path, validators=[django.core.validators.FileExtensionValidator(('7z', 'csv', 'doc', 'docx', 'jpeg', 'jpg', 'ods', 'odt', 'pdf', 'png', 'rar', 'rtf', 'svg', 'txt', 'webp', 'xls', 'xlsx', 'zip')), apps.projects.validators.validate_project_file_size])),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('client_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл проекта',
                'verbose_name_plural': 'Файлы проекта',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Запланирован'), ('in_progress', 'В работе'), ('waiting_client', 'Нужно согласование'), ('completed', 'Завершен')], default='pending', max_length=24)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('approval_required', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_stages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project')),
            ],
            options={
                'verbose_name': 'Этап проекта',
                'verbose_name_plural': 'Этапы проекта',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'updated_at'], name='project_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_email', 'updated_at'], name='project_email_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['due_at', 'status'], name='project_due_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['project', 'client_visible', 'created_at'], name='event_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevent',
            index=models.Index(fields=['manager_seen_at', 'created_at'], name='event_manager_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['project', 'status', 'sort_order'], name='stage_project_status_idx'),
        ),
    ]
