# Generated by Django 5.2.14 on 2026-07-22 17:25

import apps.projects.validators
import apps.projects.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_backfill_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file',
            field=models.FileField(storage=apps.projects.storage.PrivateProjectStorage(), upload_to=apps.projects.validators.project_file_upload_path, validators=[django.core.validators.FileExtensionValidator(('7z', 'csv', 'doc', 'docx', 'jpeg', 'jpg', 'ods', 'odt', 'pdf', 'png', 'rar', 'rtf', 'svg', 'txt', 'webp', 'xls', 'xlsx', 'zip')), apps.projects.validators.validate_project_file_size]),
        ),
    ]
