# Generated by Django 5.2.14 on 2026-07-22 21:04

from django.conf import settings
from django.db import migrations, models


def backfill_approval_states(apps, schema_editor):
    ProjectStage = apps.get_model("projects", "ProjectStage")
    ProjectStage.objects.filter(approval_required=True, approved_at__isnull=False).update(
        approval_state="approved",
        approval_decided_at=models.F("approved_at"),
    )
    ProjectStage.objects.filter(
        approval_required=True,
        approved_at__isnull=True,
        status="waiting_client",
    ).update(
        approval_state="pending",
        approval_requested_at=models.F("updated_at"),
    )


def reset_approval_states(apps, schema_editor):
    ProjectStage = apps.get_model("projects", "ProjectStage")
    ProjectStage.objects.update(
        approval_state="not_required",
        approval_requested_at=None,
        approval_decided_at=None,
        approval_comment="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='approval_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='approval_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='approval_state',
            field=models.CharField(choices=[('not_required', 'Не требуется'), ('pending', 'Ожидает решения'), ('approved', 'Согласовано'), ('changes_requested', 'Нужны изменения')], default='not_required', max_length=24),
        ),
        migrations.RunPython(backfill_approval_states, reset_approval_states),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['project', 'approval_state', 'sort_order'], name='stage_project_approval_idx'),
        ),
    ]
