# Generated by Django 5.2.14 on 2026-05-20 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_telegram_chat_id_profile_telegram_link_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('email_verify', 'Подтверждение email')], max_length=40)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код подтверждения email',
                'verbose_name_plural': 'Коды подтверждения email',
                'indexes': [models.Index(fields=['user', 'purpose', 'used_at', 'created_at'], name='accounts_em_user_id_6571f3_idx'), models.Index(fields=['email', 'purpose', 'created_at'], name='accounts_em_email_60ecc0_idx')],
            },
        ),
    ]
