# Generated by Django 5.2.16 on 2026-09-23 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название проекта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('discussion', 'Обсуждение'), ('in_progress', 'В работе'), ('review', 'Проверка'), ('completed', 'Завершён')], default='draft', max_length=24, verbose_name='Статус')),
                ('summary', models.TextField(blank=True, verbose_name='Описание')),
                ('next_action', models.CharField(blank=True, max_length=240, verbose_name='Следующий шаг')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('due_at', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='content.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['-updated_at'],
            },
        ),
    ]
