# Generated by Django 5.2.14 on 2026-05-13 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order'),
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('url', models.URLField(blank=True)),
                ('domain_name', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('development', 'В разработке'), ('review', 'На проверке'), ('live', 'Работает'), ('maintenance', 'На поддержке'), ('action_required', 'Требует внимания'), ('paused', 'Пауза')], default='planning', max_length=32)),
                ('support_plan', models.CharField(choices=[('none', 'Без поддержки'), ('basic', 'Базовая поддержка'), ('growth', 'Развитие и SEO'), ('business', 'Бизнес-сопровождение')], default='basic', max_length=32)),
                ('domain_registrar', models.CharField(blank=True, max_length=160)),
                ('domain_expires_at', models.DateField(blank=True, null=True)),
                ('hosting_provider', models.CharField(blank=True, max_length=160)),
                ('hosting_plan', models.CharField(blank=True, max_length=160)),
                ('hosting_expires_at', models.DateField(blank=True, null=True)),
                ('ssl_provider', models.CharField(blank=True, default="Let's Encrypt", max_length=160)),
                ('ssl_expires_at', models.DateField(blank=True, null=True)),
                ('ssl_auto_renew', models.BooleanField(default=True)),
                ('last_backup_at', models.DateTimeField(blank=True, null=True)),
                ('backup_frequency', models.CharField(blank=True, default='Еженедельно', max_length=120)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('analytics_connected', models.BooleanField(default=False)),
                ('seo_baseline_ready', models.BooleanField(default=False)),
                ('support_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to='leads.lead')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sites', to='billing.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиентский сайт',
                'verbose_name_plural': 'Клиентские сайты',
                'ordering': ('status', 'title'),
            },
        ),
    ]
