# Generated by Django 5.2.14 on 2026-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_managedsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_requisites',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
