# Generated by Django 5.2.14 on 2026-05-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_invoice_client_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='note',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
