# Generated by Django 5.2.14 on 2026-07-21 15:32

from django.db import migrations, models


def mark_historical_duplicate_payments(apps, schema_editor):
    payment_model = apps.get_model("billing", "Payment")
    invoice_ids = (
        payment_model.objects.filter(status="succeeded")
        .values_list("invoice_id", flat=True)
        .distinct()
    )
    for invoice_id in invoice_ids:
        successful_ids = list(
            payment_model.objects.filter(invoice_id=invoice_id, status="succeeded")
            .order_by("pk")
            .values_list("pk", flat=True)
        )
        if len(successful_ids) > 1:
            payment_model.objects.filter(pk__in=successful_ids[1:]).update(status="duplicate")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успешен'), ('duplicate', 'Повторная оплата'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
        migrations.RunPython(mark_historical_duplicate_payments, migrations.RunPython.noop),
    ]
