# Generated by Django 5.2.14 on 2026-07-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_operation_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_state_code',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успешен'), ('duplicate', 'Повторная оплата'), ('review', 'Требует проверки'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
