# Generated by Django 5.2.14 on 2026-07-22 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_payment_last_reconciled_at_and_more'),
        ('leads', '0005_quickconsultation_pending_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'created_at'], name='invoice_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='managedsite',
            index=models.Index(fields=['status', 'title'], name='site_status_title_idx'),
        ),
        migrations.AddIndex(
            model_name='managedsite',
            index=models.Index(fields=['domain_expires_at'], name='site_domain_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='managedsite',
            index=models.Index(fields=['hosting_expires_at'], name='site_hosting_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='managedsite',
            index=models.Index(fields=['ssl_expires_at'], name='site_ssl_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['due_at', 'status'], name='order_due_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'status', 'created_at'], name='payment_provider_state_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'paid_at'], name='payment_status_paid_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='invoice_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_item_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='invoice_item_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_amount_min__isnull', True), ('estimated_amount_min__gte', 0), _connector='OR'), name='order_estimate_min_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_amount_max__isnull', True), ('estimated_amount_max__gte', 0), _connector='OR'), name='order_estimate_max_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_amount_min__isnull', True), ('estimated_amount_max__isnull', True), ('estimated_amount_max__gte', models.F('estimated_amount_min')), _connector='OR'), name='order_estimate_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
    ]
