# Generated by Django 5.2.14 on 2026-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('robokassa', 'Robokassa'), ('telegram', 'Telegram'), ('system', 'Система')], max_length=30)),
                ('status', models.CharField(choices=[('info', 'Информация'), ('success', 'Успешно'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=20)),
                ('title', models.CharField(max_length=220)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие интеграции',
                'verbose_name_plural': 'События интеграций',
                'ordering': ('-created_at',),
            },
        ),
    ]
