# Generated by Django on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBotSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_enabled", models.BooleanField(default=False)),
                ("bot_token", models.TextField(blank=True)),
                ("admin_chat_id", models.CharField(blank=True, max_length=80)),
                ("webhook_secret", models.TextField(blank=True)),
                ("webhook_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки Telegram-бота",
                "verbose_name_plural": "Настройки Telegram-бота",
            },
        ),
    ]
