# Generated by Django on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_telegrambotsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambotsettings",
            name="last_update_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
