# Generated by Django 5.2.14 on 2026-05-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_telegrambotsettings_last_update_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotsettings',
            name='bot_username',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
