# Generated by Django 5.2.14 on 2026-05-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_telegrambotsettings_bot_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobokassaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('merchant_login', models.CharField(blank=True, max_length=160)),
                ('password1', models.TextField(blank=True)),
                ('password2', models.TextField(blank=True)),
                ('test_mode', models.BooleanField(default=True)),
                ('hash_algorithm', models.CharField(default='md5', max_length=32)),
                ('payment_url', models.URLField(default='https://auth.robokassa.ru/Merchant/Index.aspx')),
                ('receipt_enabled', models.BooleanField(default=True)),
                ('receipt_sno', models.CharField(blank=True, max_length=40)),
                ('receipt_tax', models.CharField(default='none', max_length=40)),
                ('receipt_payment_method', models.CharField(default='full_payment', max_length=40)),
                ('receipt_payment_object', models.CharField(default='service', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки Robokassa',
                'verbose_name_plural': 'Настройки Robokassa',
            },
        ),
    ]
