# Generated by Django 5.2.14 on 2026-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_robokassasettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickConsultationBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('bot_token', models.TextField(blank=True)),
                ('bot_username', models.CharField(blank=True, max_length=80)),
                ('admin_chat_id', models.CharField(blank=True, max_length=80)),
                ('webhook_secret', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('last_update_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки бота быстрых консультаций',
                'verbose_name_plural': 'Настройки бота быстрых консультаций',
            },
        ),
    ]
