# Generated by Django 5.2.14 on 2026-07-21 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_quickconsultationbotsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('telegram_update', 'Обработка Telegram webhook'), ('quick_telegram_method', 'Отправка метода быстрого Telegram-бота'), ('quick_webhook_event', 'Запись webhook быстрого Telegram-бота'), ('quick_consultation_created', 'Новая быстрая консультация'), ('invoice_issued_email', 'Email о выставленном счете'), ('invoice_issued_admin_tg', 'Счет: Telegram администратору'), ('invoice_issued_client_tg', 'Счет: Telegram клиенту'), ('payment_success_admin_email', 'Оплата: email администратору'), ('payment_success_client_email', 'Оплата: email клиенту'), ('payment_success_admin_tg', 'Оплата: Telegram администратору'), ('payment_success_client_tg', 'Оплата: Telegram клиенту'), ('quick_payment_success', 'Оплата: быстрый Telegram-бот'), ('duplicate_payment_email', 'Повторная оплата: email'), ('duplicate_payment_tg', 'Повторная оплата: Telegram')], max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('deduplication_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Выполняется'), ('retry', 'Ожидает повтора'), ('succeeded', 'Выполнено'), ('failed', 'Требует внимания')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Исходящая операция',
                'verbose_name_plural': 'Исходящие операции',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'available_at'], name='out_task_status_available'), models.Index(fields=['task_type', 'created_at'], name='out_task_type_created')],
            },
        ),
    ]
