# Generated by Django 5.2.14 on 2026-07-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_outboundtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboundtask',
            name='task_type',
            field=models.CharField(choices=[('telegram_update', 'Обработка Telegram webhook'), ('quick_telegram_method', 'Отправка метода быстрого Telegram-бота'), ('quick_webhook_event', 'Запись webhook быстрого Telegram-бота'), ('quick_consultation_created', 'Новая быстрая консультация'), ('invoice_issued_email', 'Email о выставленном счете'), ('invoice_issued_admin_tg', 'Счет: Telegram администратору'), ('invoice_issued_client_tg', 'Счет: Telegram клиенту'), ('payment_success_admin_email', 'Оплата: email администратору'), ('payment_success_client_email', 'Оплата: email клиенту'), ('payment_success_admin_tg', 'Оплата: Telegram администратору'), ('payment_success_client_tg', 'Оплата: Telegram клиенту'), ('quick_payment_success', 'Оплата: быстрый Telegram-бот'), ('duplicate_payment_email', 'Повторная оплата: email'), ('duplicate_payment_tg', 'Повторная оплата: Telegram'), ('payment_review_email', 'Спорная оплата: email'), ('payment_review_tg', 'Спорная оплата: Telegram')], max_length=64),
        ),
    ]
