# Generated by Django 5.2.14 on 2026-07-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_outboundtask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationevent',
            name='payload_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['provider', 'created_at'], name='integration_provider_date_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['status', 'created_at'], name='integration_status_date_idx'),
        ),
    ]
