# Generated by Django 5.2.14 on 2026-07-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_integrationevent_payload_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robokassasettings",
            name="hash_algorithm",
            field=models.CharField(default="sha256", max_length=32),
        ),
    ]
