# Generated by Django 5.2.14 on 2026-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(unique=True)),
                ('industry', models.CharField(blank=True, max_length=160)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('result', models.TextField()),
                ('stack', models.CharField(blank=True, max_length=260)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=220)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ('sort_order', 'question'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('service_type', models.CharField(choices=[('python', 'Python-разработка'), ('website', 'Сайт или лендинг'), ('seo', 'SEO'), ('automation', 'Автоматизация'), ('consulting', 'Консалтинг'), ('integration', 'Бизнес-интеграции')], max_length=30)),
                ('short_description', models.CharField(max_length=260)),
                ('full_description', models.TextField(blank=True)),
                ('business_value', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True, help_text='По одному пункту на строку.')),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='TemplateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('template_type', models.CharField(choices=[('starter', 'Стартовый шаблон'), ('module', 'Модуль'), ('checklist', 'Чеклист'), ('package', 'Пакет работ')], max_length=30)),
                ('short_description', models.CharField(max_length=260)),
                ('contents', models.TextField(blank=True, help_text='Что входит. По одному пункту на строку.')),
                ('implementation_notes', models.TextField(blank=True)),
                ('is_paid_ready', models.BooleanField(default=False, help_text='Можно будет продавать через Robokassa.')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Шаблон/продукт',
                'verbose_name_plural': 'Шаблоны и продукты',
                'ordering': ('sort_order', 'title'),
            },
        ),
    ]
