# Generated by Django 5.2.14 on 2026-05-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateproduct',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='templateproduct',
            name='conversion_focus',
            field=models.CharField(blank=True, default='', max_length=260),
        ),
        migrations.AddField(
            model_name='templateproduct',
            name='industry',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='templateproduct',
            name='template_type',
            field=models.CharField(choices=[('website', 'Шаблон сайта'), ('starter', 'Стартовый шаблон'), ('module', 'Модуль'), ('checklist', 'Чеклист'), ('package', 'Пакет работ')], max_length=30),
        ),
    ]
