# Generated by Django 5.2.14 on 2026-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_templateproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('python', 'Python-разработка'), ('website', 'Сайт или лендинг'), ('support', 'Поддержка сайтов'), ('telegram', 'Telegram-боты'), ('seo', 'SEO'), ('automation', 'Автоматизация'), ('consulting', 'Консалтинг'), ('integration', 'Бизнес-интеграции')], max_length=30),
        ),
    ]
