# Generated by Django 5.2.14 on 2026-05-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость, ₽'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_note',
            field=models.CharField(blank=True, max_length=180, verbose_name='Комментарий к цене'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_prefix',
            field=models.CharField(blank=True, default='от', max_length=30, verbose_name='Префикс цены'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(blank=True, default='за проект', max_length=80, verbose_name='Единица цены'),
        ),
    ]
