# Generated by Django 5.2.14 on 2026-07-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_retired_services'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_published', 'service_type', 'sort_order'], name='service_public_type_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_published', 'is_featured', 'sort_order'], name='service_featured_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__isnull', True), ('price_amount__gt', 0), _connector='OR'), name='service_price_positive'),
        ),
    ]
