# Generated by Django 5.2.16 on 2026-08-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_service_service_public_type_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=160, verbose_name='Имя клиента')),
                ('client_details', models.CharField(blank=True, max_length=180, verbose_name='Компания или подпись')),
                ('project_title', models.CharField(blank=True, max_length=220, verbose_name='Проект')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показывать первым')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
    ]
