# Generated by Django 5.2.16 on 2026-08-29 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='publication_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Согласие на публикацию'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='Отправил клиент'),
        ),
    ]
