# Generated by Django 5.2.14 on 2026-07-22 00:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=16)),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=80)),
                ('object_label', models.CharField(max_length=220)),
                ('channel', models.CharField(default='office', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие аудита',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['object_type', 'object_id', 'created_at'], name='audit_object_created_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(max_length=120)),
                ('subject_id', models.CharField(max_length=80)),
                ('document_type', models.CharField(choices=[('offer', 'Публичная оферта'), ('privacy', 'Политика обработки данных')], max_length=20)),
                ('document_scope', models.CharField(choices=[('general', 'Основной сайт'), ('fast', 'Быстрые консультации')], max_length=20)),
                ('document_version', models.CharField(max_length=40)),
                ('document_checksum', models.CharField(max_length=64)),
                ('channel', models.CharField(choices=[('web', 'Сайт'), ('account', 'Личный кабинет'), ('telegram', 'Telegram-бот')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Принятие документа',
                'verbose_name_plural': 'Принятые документы',
                'ordering': ('-accepted_at',),
                'indexes': [models.Index(fields=['subject_type', 'subject_id', 'accepted_at'], name='consent_subject_date_idx'), models.Index(fields=['document_type', 'accepted_at'], name='consent_document_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('subject_type', 'subject_id', 'document_type', 'document_scope', 'document_checksum', 'channel'), name='unique_document_acceptance')],
            },
        ),
    ]
