# Generated by Django 5.2.14 on 2026-07-22 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=180, unique=True)),
                ('severity', models.CharField(choices=[('warning', 'Предупреждение'), ('error', 'Критическая ошибка')], max_length=16)),
                ('title', models.CharField(max_length=220)),
                ('message', models.TextField()),
                ('details_hash', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('first_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Эксплуатационное предупреждение',
                'verbose_name_plural': 'Эксплуатационные предупреждения',
                'ordering': ('-is_active', '-last_detected_at'),
                'indexes': [models.Index(fields=['is_active', 'severity', 'last_detected_at'], name='ops_alert_state_date_idx')],
            },
        ),
    ]
