# Generated by Django 5.2.14 on 2026-05-12 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=220)),
                ('service_type', models.CharField(blank=True, max_length=120)),
                ('task', models.TextField()),
                ('source', models.CharField(choices=[('form', 'Форма сайта'), ('messenger', 'Мессенджер'), ('admin', 'Админка')], default='form', max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('qualifying', 'На разборе'), ('proposal', 'Готовится предложение'), ('won', 'Переведена в заказ'), ('lost', 'Закрыта')], default='new', max_length=20)),
                ('page_title', models.CharField(blank=True, max_length=220)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
    ]
