# Generated by Django 5.2.14 on 2026-05-29 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoiceitem_note'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telegram_chat_id', models.CharField(max_length=80)),
                ('telegram_user_id', models.CharField(blank=True, max_length=80)),
                ('telegram_username', models.CharField(blank=True, max_length=120)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('client_name', models.CharField(blank=True, max_length=180)),
                ('question', models.TextField(blank=True)),
                ('manager_response', models.TextField(blank=True)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('waiting_question', 'Ждем вопрос'), ('new', 'Новая'), ('in_discussion', 'В консультации'), ('invoiced', 'Счет отправлен'), ('paid', 'Оплачена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='waiting_question', max_length=32)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_consultation', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Быстрая консультация',
                'verbose_name_plural': 'Быстрые консультации',
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
