# Generated by Django 5.2.14 on 2026-05-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_quickconsultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickconsultation',
            name='status',
            field=models.CharField(choices=[('waiting_question', 'Ждем вопрос'), ('waiting_payment_amount', 'Ждем сумму оплаты'), ('new', 'Новая'), ('in_discussion', 'В консультации'), ('invoiced', 'Счет отправлен'), ('paid', 'Оплачена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='waiting_question', max_length=32),
        ),
    ]
