# Generated by Django 5.2.14 on 2026-07-22 00:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_invoice_status_created_idx_and_more'),
        ('leads', '0005_quickconsultation_pending_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='lead_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['source', 'created_at'], name='lead_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='quickconsultation',
            index=models.Index(fields=['status', 'updated_at'], name='quick_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='quickconsultation',
            index=models.Index(fields=['telegram_chat_id', 'status', 'updated_at'], name='quick_chat_state_idx'),
        ),
        migrations.AddConstraint(
            model_name='quickconsultation',
            constraint=models.CheckConstraint(condition=models.Q(('quoted_amount__isnull', True), ('quoted_amount__gt', 0), _connector='OR'), name='quick_quote_positive'),
        ),
    ]
