# Generated by Django 5.2.16 on 2026-09-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(max_length=260, verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(max_length=120, verbose_name='Категория')),
                ('short_description', models.CharField(max_length=260, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('features', models.TextField(blank=True, help_text='По одному пункту на строку.', verbose_name='Что сделано')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='works/', verbose_name='Изображение')),
                ('preview_static', models.CharField(blank=True, max_length=220, verbose_name='Изображение из static')),
                ('demo_link', models.URLField(blank=True, verbose_name='Ссылка на сайт')),
                ('demo_static', models.CharField(blank=True, max_length=220, verbose_name='Демо из static')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'пример работы',
                'verbose_name_plural': 'примеры работ',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
